config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :chats
  end


  namespace :api do
    namespace :v1 do
    resources :users do
    member do
      get :name
    end
    end
    end
  end

  root to: "main#index"
  get "search", to: "search#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :conversations do
    resources :messages
  end

  get "dash", to: "job_positions#job"

  resources :job_positions

  post "/job_positions/new", to: "job_positions#create"

  patch "/job_positions/:id/edit", to: "job_positions#update"

  get "/job_position/:id", to: "job_positions#destroy", as: "job_position_delete"

  resources :job_fields

  post "/job_fields/new", to: "job_fields#create"

  patch "/job_fields/:id/edit", to: "job_fields#update"

  get "/job_field/:id", to: "job_fields#destroy", as: "job_field_delete"

  get "/job_navigations/:id/edit", to: "job_navigations#edit", as: "edit_job_navigation"

  resources :job_navigations

  get "new_job_navigation", to: "job_navigations#new"

  post "/job_navigations/new", to: "job_navigations#create"

  get "/job_navigations/:id/toggle_is_approved", to: "job_navigations#toggle_is_approved",
                                                 as: "toggle_is_approved"

  get "/job_navigations/:id/destroy", to: "job_navigations#destroy", as: "job_navigation_del"

  get "/job_navigation", to: "job_navigations#show"

  resources :job_navigations, only: %i[index destroy] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  resources :job_navigations, only: %i[show] do
    resources :reviews
  end

  resources :job_navigations, only: %i[show edit] do
    resources :applies
  end

  post "/job_navigation", to: "job_navigations#show"

  resources :job_navigations do
    member do
      post "like", to: "job_navigations#vote"
    end
  end

  resources :users

  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  post "/users/:id/accept", to: "users#accept", as: "accept"
  post "/users/:id/decline", to: "users#decline", as: "decline"
  post "/users/:id/cancel", to: "users#cancel", as: "cancel"

  get "/user/:id", to: "users#destroy", as: "user_delete"

  get "notify", to: "users#notify"

  get "connection", to: "users#connection"

  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  resources :user_accounts

  get "new_user_account", to: "user_accounts#new"

  resources :job_navigations do
    resources :likes
  end

  resources :notifications

  resources :notifies

  get "/user/:id/profile", to: "users#profile", as: "profile"

  get "applied", to: "job_navigations#applied"
  get "feed", to: "job_navigations#feed"
  get "recommended", to: "users#recommended"

  get "dashboard", to: "user_accounts#dashboard"

  get "network", to: "users#network"

  get "/user/:id/follower", to: "users#follower", as: "follower"

  get "/user/:id/following", to: "users#following", as: "following"

  get "posts", to: "job_navigations#posts"

  get "/auth/:provider/callback", to: "sessions#linkedin"
  get "/auth/linkedin/callback", to: "sessions#linkedin_callback"

  get "remove_matching_user/:id", to: "users#remove_matching_user", as: "remove_matching_user"
end

app/models/user_account.rb
# frozen_string_literal: true

class UserAccount < ApplicationRecord
  belongs_to :user
  has_many_attached :certificate
  has_one_attached :picture
  has_one_attached :cv
  validates :username, allow_blank: true, length: { minimum: 3, maximum: 50 }
  validates :gmail, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'must be a valid email address' }
  validates :job, presence: true
  validates :link, allow_blank: true, format: %r{\Ahttp(s)://.*?\.linkedin\.com/}
  validates :picture, allow_blank: true, attached: true, content_type: %i[png jpg jpeg]
  validates :certificate, allow_blank: true, attached: true, content_type: %i[png jpg jpeg]
  validates :cv, allow_blank: true, attached: true, content_type: [:pdf]

  before_save do
    job.gsub!(/[\[\]"]/, '') if attribute_present?('job')
  end

  def thumbnail
    image.variant(resize: '100*100')
  end
end

app/controllers/api/v1/user_accounts_controller.rb
class Api::V1::UserAccountsController < ApplicationController
end

app/controllers/user_accounts_controller.rb
# frozen_string_literal: true

class UserAccountsController < ApplicationController
  before_action :set_current_user
  before_action :require_user_logged_in!

  def dashboard; end

  def index
    @user_account = UserAccount.all
  end

  def new
    @user_account = UserAccount.new
  end

  def create
    @user_account = @current_user.user_accounts.new(user_account_params)
    respond_to do |format|
      if @user_account.save
        format.html { redirect_to user_accounts_path, notice: 'Your Informmation saved successfully .' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @user_account = UserAccount.find(params[:id])
  end

  def update
    @user_account = UserAccount.find(params[:id])
    if @user_account.update(user_account_params)

      redirect_to user_accounts_path, notice: 'Successfully updated Your Profile'
    else

      render :edit
    end
  end

  private

  def user_account_params
    params.require(:user_account).permit(:gmail, :username, :link, :expericence, :organisation, :skill,
                                         :picture, :cv, :qualification, :notification, :cvdownload, :bio, certificate: [], job: [])
  end
end

app/helpers/api/v1/user_accounts_helper.rb
module Api::V1::UserAccountsHelper
end

app/views/user_accounts/dashboard.html.erb
<h3 class="card-subtitle mb-3 text-dark head size center">Your Connection's Posts</h3> 
<div class="wrapperjob"> 
  <% @current_user.following.each do |user| %>
    <% user.job_navigations.each do |job_navigation| %>
      <% if job_navigation.is_approved == true  %> 
        <section class="card my-5 shadow card-background "> 
          <div class="card-body">
            <div class=" mb-3  outer">
              <% if user.user_accounts.count > 0 %>
                <% if user.user_accounts.first.picture.attached? %>
                  <%= image_tag user.user_accounts.first.picture.url  %>
                <% else %>
                  <%= image_tag 'default.png' %>
                <% end %>
              <% else %>
                <%= image_tag 'default.png' %>
              <% end %>
            </div>
            <div class=" mb-3">
              <h5> By :</h5>
              <%= link_to job_navigation.user.username, profile_path(user), class: "text-primary link" %>
            </div>
            <div class=" mb-3 ">
              <h5>JOB TITLE : </h5>
              <%= job_navigation.jobtitle%>
            </div> 
            <div class=" mb-3 ">
              <h5>JOB DESCRIPTION :</h5>
              <%= job_navigation.jobdescription %>
            </div>
            <div class=" mb-3 "> 
              <h5>NUMBER OF VACANCY :</h5>
              <%= job_navigation.vacancy %>
            </div>
            <div class=" mb-3 ">
              <h5>SKILL:</h5>
              <%= job_navigation.skill%>
            </div>
            <div class=" mb-3 ">
              <h5>JOB ROLE:</h5>
              <%= job_navigation.jobrole%>
            </div>
            <div class=" mb-3 ">
              <h5>JOB SECTOR:</h5>
              <%= job_navigation.jobsector%>
            </div>
            <p class=" mb-3 "><%= job_navigation.likes.count %> <%= (job_navigation.likes.count) == 1 ? 'Like' : 'Likes' %></p>
            <% pre_like = job_navigation.likes.find {|like| like.user_id == @current_user.id} %>
            <div class = "center">
              <% if pre_like %>
                <%= button_to 'Unlike', job_navigation_like_path(job_navigation, pre_like), method: :delete %>
              <% else %>
                <%= button_to 'Like', job_navigation_likes_path(job_navigation), method: :post %>
              <% end %>
            </div>
            <%= link_to 'Details', job_navigation_path(job_navigation) , class:"text-primary link" %>
          </div>
        </section>  
      <% end %>      
    <% end %>   
  <% end %> 
</div>

app/views/user_accounts/edit.html.erb
<%= form_with model: @user_account, :html => { :'data-ajax' => false } do |form| %>
  <%= form.hidden_field :user_id, value: @user_id %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>
  <section class="card my-5 shadow size card-background">
    <div class="card-body">
      <h3 class="card-subtitle mb-3 ">User Information Form</h3>
      <div class=" mb-3 ">
        <%= form.label :gmail, class: 'required' %>
        <%= form.text_field :gmail, class: "form-control" , placeholder: "Developer"%>
      </div>
      <div class=" mb-3 ">
        <%= form.label :username %>
        <%= form.text_field :username, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :link%>
        <%= form.text_field :link, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :qualification, class: 'required' %>
        <%= form.select :qualificatioon, ["BA", "B.Sc", "B.com" ,"B.Tech" , "BE"] %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :experience, class: 'required' %>
        <%= form.select :experience, ["Fresher", "0-5", "5-10", "10-15" ,"15-20" , "20-25"] %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :orgganisation, class:'inputt'%>
        <%= form.text_field :organisation, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :skill %>
        <%= form.text_field :skill, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :Bio %>
        <%= form.text_field :bio, class: "form-control" %>
      </div>
        <div class="field ">
         <h5 class= 'required' >job </h5>
        <%= label_tag 'job_developer', 'Developer' %>
        <%= check_box_tag 'user_account[job][]', 'Developer', checked('Developer'), id: 'job_developer' %>
        <%= label_tag 'job_webEngineer', 'WebEngineer' %>
        <%= check_box_tag 'user_account[job][]', 'WebEngineer', checked('WebEngineer'), id: 'job_webEngineer' %>
        <%= label_tag 'job_engineer', 'Engineer' %>
        <%= check_box_tag 'user_account[job][]', 'Engineer', checked('Engineer'), id: 'job_engineer' %>
        <%= label_tag 'job_receiptionist', 'Receiptionist' %>
        <%= check_box_tag 'user_account[job][]', 'Receiptionist', checked('Receiptionist'), id: 'job_receiptionist' %>
        <%= label_tag 'job_cook', 'Cook' %>
        <%= check_box_tag 'user_account[job][]', 'Cook', checked('Cook'), id: 'job_cook' %>
        <%= label_tag 'job_caretaker', 'Caretaker' %>
        <%= check_box_tag 'user_account[job][]', 'Caretaker', checked('Caretaker'), id: 'job_caretaker' %>
      </div>
      <div class="mb-3 navpic ">
        <%= form.label :picture, "Profile Picture" %> 
        <%=form.file_field :picture %>
          <% if @user_account.picture.attached? %>
            Current <%= image_tag @user_account.picture.url  %>
            <% else %>
            Attach Picture
          <% end %>
      </div>
      <div class="mb-3 ">
        <%= form.label :cv, "Upload Cv" %>
        <%=form.file_field :cv %>
        <% if @user_account.cv.attached? %>
            Current <%= link_to "Your CV", @user_account.cv.url , class:"link"%> 
            <% else %>
            Attach CV
            <% end %>
      </div> 
      <div class="mb-3 navpic">
        <%= form.label :certificate, class:"cv" %> 
        <%= form.file_field :certificate, multiple: true %> 
          <% if @user_account.certificate.attached? %>
            <% @user_account.certificate.each do |certificate| %>
              <%= image_tag certificate.url   %>
            <% end %>
          <% end %>
      </div>  
      <div class="mb-3  ">
        <%= form.label :notification %>
        <%= form.radio_button :notification, 'Yes' %> Yes <br/>
        <%= form.radio_button :notification, 'No' %> No <br/>
      </div>
    </div>
    <div class="d-flex text-center gap-3">
      <%= form.submit "Update" , class: "btn btn-primary" %>
    </div>
  </section>
<% end %>

   


    

app/views/user_accounts/index.html.erb
<% if @current_user.user_accounts.count == 0 %>
<div class="center">
  <a class="btn btn-primary" href="new_user_account" role="button">Fill</a>
  <div>
  [Click Here To Give Information About Yourself For Better Experience]
  </div>
  </div>
<% else %>
  <% @current_user.user_accounts.each do |user_account| %>
    <section class="card my-5 shadow size card-background">
      <div class="card-body">
        <h3 class="card-subtitle mb-3">Your Information</h3>
        <div class=" mb-3  outer">
          <% if user_account.picture.attached? %>
            <%= image_tag user_account.picture.url   %>
          <% else %>
            <%= image_tag("https://h-o-m-e.org/wp-content/uploads/2022/04/Blank-Profile-Picture-3.jpg") %>
          <% end %>
        </div>
          <div class=" mb-3 ">
            <h5> Email </h5>
            <%= user_account.gmail %>
          </div>
            <div class=" mb-3 ">
            <h5> username </h5>
            <%= user_account.username  %>
          </div> 
          <div class=" mb-3 ">
            <h5> Profile Link </h5>
            <%= user_account.link %>
          </div>
          <div class=" mb-3 ">
            <h5> Qualificatioon </h5>
            <%= user_account.qualification %>
          </div>
          <div class=" mb-3 ">
            <h5> Organisation </h5>
            <%= user_account.organisation %>
          </div>
          <div class=" mb-3 ">
            <h5> skill </h5>
            <%= user_account.skill %>
          </div>
          <div class=" mb-3 ">
            <h5> Bio </h5>
            <%= user_account.bio %>
          </div>
          <div class=" mb-3 ">
            <h5> Job </h5>
            <%= user_account.job %>
          </div>
          <div class=" mb-3 ">
            <h5> CV </h5>
            <%= link_to "Your CV", user_account.cv.url , class:"link"%> 
          </div>
          <div class=" mb-3  certificate">
            <h5> Certificates </h5>
              <% user_account.certificate.each do |certificate| %>
                <%= image_tag certificate.url   %>
              <% end %>
          </div>
           <%= link_to edit_user_account_path(user_account), class: " text-primary d-flex flex-column align-items-center" do %>
    <%= icon('fa fa-pen fa-2x') %>
    
  <% end %>
         
    </section>
  <% end %>
<% end %>


  

app/views/user_accounts/new.html.erb
<%= form_with model: @user_account, :html => { multipart: true } do |form| %>
  <%= form.hidden_field :user_id, value: @user_id %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
      </div>
  <% end %>
  <section class="card my-5 shadow size card-background">
    <div class="card-body">
      <h3 class="card-subtitle mb-3">User Information Form</h3>
      <div class=" mb-3 ">
        <%= form.label :gmail, class: 'required' %>
        <%= form.text_field :gmail, class: "form-control" %> 
      </div>
      <div class=" mb-3 ">
        <%= form.label :username %>
        <%= form.text_field :username, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :linkedIn_Profile%>
        <%= form.text_field :link, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :qualification, class: 'required' %>
        <%= form.select :qualification, ["BA", "B.Sc", "B.com" ,"B.Tech" , "BE"], required: true %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :experience, class: 'required' %>
        <%= form.select :experience, [ "Fresher", "0-5", "5-10", "10-15" ,"15-20" , "20-25"] %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :organisation, class:'inputt'%>
        <%= form.text_field :organisation, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :skill %>
        <%= form.text_field :skill, class: "form-control" %>
      </div>
      <div class=" mb-3 ">
        <%= form.label :Bio %>
        <%= form.text_field :bio, class: "form-control" %> 
      </div>
      <div class="mb-3 ">
        <h5 class= 'required' >job </h5>
        <%= label_tag 'job_developer', 'Developer' %>
        <%= check_box_tag 'user_account[job][]', 'Developer', checked('Developer'), id: 'job_developer' %>
        <%= label_tag 'job_webEngineer', 'WebEngineer' %>
        <%= check_box_tag 'user_account[job][]', 'WebEngineer', checked('WebEngineer'), id: 'job_webEngineer' %>
        <%= label_tag 'job_engineer', 'Engineer' %>
        <%= check_box_tag 'user_account[job][]', 'Engineer', checked('Engineer'), id: 'job_engineer' %>
        <%= label_tag 'job_receiptionist', 'Receiptionist' %>
        <%= check_box_tag 'user_account[job][]', 'Receiptionist', checked('Receiptionist'), id: 'job_receiptionist' %>
        <%= label_tag 'job_cook', 'Cook' %>
        <%= check_box_tag 'user_account[job][]', 'Cook', checked('Cook'), id: 'job_cook' %>
        <%= label_tag 'job_caretaker', 'Caretaker' %>
        <%= check_box_tag 'user_account[job][]', 'Caretaker', checked('Caretaker'), id: 'job_caretaker' %>
      </div> 
      <div class="mb-3 ">
        <%= form.label :picture, "Profile Picture" %> 
        <%=form.file_field :picture %>
      </div>
      <div class="mb-3 ">
        <%= form.label :cv, class:"cv" %> 
        <%=form.file_field :cv, :oninput=> "return cvdownload()" %> 
      </div>  
      <script>
      function cvdownload(){
        document.getElementById("download").classList.remove('sel').add('show');
      }
      </script>
      <div class="mb-3  sel" id="download" >
        <%= form.label :Download %>(Who can Download Your Cv)</br>
        <%= form.radio_button :cvdownload,'Any Body' %> Any Body<br/>
        <%= form.radio_button :cvdownload,'No Body' %> No Body <br/>
        <%= form.radio_button :cvdownload,'Connections' %> Connections <br/> 
      </div>
      <div class="mb-3 ">
        <%= form.label :certificate, class:"cv" %> 
        <%= form.file_field :certificate, multiple: true %> 
      </div>  
      <div class="mb-3  ">
        <%= form.label :notification %>
        <%= form.radio_button :notification, 'Yes' %> Yes <br/>
        <%= form.radio_button :notification, 'No' %> No <br/>
      </div>
      <div class="d-flex text-center gap-3 ">
        <%= form.submit "submit" , class: "btn btn-primary" %>
        <%= link_to 'Cancel', request.referer, class: "btn btn-primary"  %>
      </div>
    </div>
  </section>
<% end %>

   


    