config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :chats
  end


  namespace :api do
    namespace :v1 do
    resources :users do
    member do
      get :name
    end
    end
    end
  end

  root to: "main#index"
  get "search", to: "search#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :conversations do
    resources :messages
  end

  get "dash", to: "job_positions#job"

  resources :job_positions

  post "/job_positions/new", to: "job_positions#create"

  patch "/job_positions/:id/edit", to: "job_positions#update"

  get "/job_position/:id", to: "job_positions#destroy", as: "job_position_delete"

  resources :job_fields

  post "/job_fields/new", to: "job_fields#create"

  patch "/job_fields/:id/edit", to: "job_fields#update"

  get "/job_field/:id", to: "job_fields#destroy", as: "job_field_delete"

  get "/job_navigations/:id/edit", to: "job_navigations#edit", as: "edit_job_navigation"

  resources :job_navigations

  get "new_job_navigation", to: "job_navigations#new"

  post "/job_navigations/new", to: "job_navigations#create"

  get "/job_navigations/:id/toggle_is_approved", to: "job_navigations#toggle_is_approved",
                                                 as: "toggle_is_approved"

  get "/job_navigations/:id/destroy", to: "job_navigations#destroy", as: "job_navigation_del"

  get "/job_navigation", to: "job_navigations#show"

  resources :job_navigations, only: %i[index destroy] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  resources :job_navigations, only: %i[show] do
    resources :reviews
  end

  resources :job_navigations, only: %i[show edit] do
    resources :applies
  end

  post "/job_navigation", to: "job_navigations#show"

  resources :job_navigations do
    member do
      post "like", to: "job_navigations#vote"
    end
  end

  resources :users

  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  post "/users/:id/accept", to: "users#accept", as: "accept"
  post "/users/:id/decline", to: "users#decline", as: "decline"
  post "/users/:id/cancel", to: "users#cancel", as: "cancel"

  get "/user/:id", to: "users#destroy", as: "user_delete"

  get "notify", to: "users#notify"

  get "connection", to: "users#connection"

  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  resources :user_accounts

  get "new_user_account", to: "user_accounts#new"

  resources :job_navigations do
    resources :likes
  end

  resources :notifications

  resources :notifies

  get "/user/:id/profile", to: "users#profile", as: "profile"

  get "applied", to: "job_navigations#applied"
  get "feed", to: "job_navigations#feed"
  get "recommended", to: "users#recommended"

  get "dashboard", to: "user_accounts#dashboard"

  get "network", to: "users#network"

  get "/user/:id/follower", to: "users#follower", as: "follower"

  get "/user/:id/following", to: "users#following", as: "following"

  get "posts", to: "job_navigations#posts"

  get "/auth/:provider/callback", to: "sessions#linkedin"
  get "/auth/linkedin/callback", to: "sessions#linkedin_callback"

  get "remove_matching_user/:id", to: "users#remove_matching_user", as: "remove_matching_user"
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
  scope :latest_first, -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :set_current_user

  def index
    @notifications = @current_user.notifications.latest_first
    @notifies = @current_user.notifies.where("id IN (
      SELECT MIN(id) FROM notifies WHERE user_id = ? GROUP BY job_navigation_id
    )", @current_user.id).latest_first
  end

  def destroy
    @notification = Notification.find(params[:id])
    return unless @notification.destroy

    redirect_to request.referer, notice: 'Notification Deleted'
  end
end

app/views/notifications/index.html.erb
<% @current_user.follow_requests.each do |request| %>
  <section class="card my-5 shadow size card-background1">
    <div class="card-body">
      <% user = request.followerable %>
        <div class = "outer mb3">
          <% if user.user_accounts.count > 0 %>
            <% if user.user_accounts.first.picture.attached? %>
              <%= image_tag user.user_accounts.first.picture.url  %>
            <% else %>
              <%= image_tag 'default.png' %>
            <% end %>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
        </div>
        <h3>-</h3>
      <%= link_to request.followerable.username, profile_path(user), class: "text-primary link" %> sent a connection request
      <div class = "mb3 flexrow">
        <%= button_to "Accept", accept_path(request.followerable) %>
        <%= button_to "Decline", decline_path(request.followerable) %> 
      </div>
    </div>
  </section>
<% end %>

<% if @current_user.notifies.any? %>
  <% @notifies.each do |notify| %>
    <% time = notify.created_at %>
    <% exp_time = time + 38.days  %>
    <% if Time.now < exp_time  %>
      <section class="card my-5 shadow size card-background">
        <div class="card-body "> 
          A new job looking for <%= link_to notify.job_navigation.jobtitle , job_navigation_path(notify.job_navigation_id) %>
          has been posted that matches your interest and skill
        <div class = "text-white-50">
          <%= time_ago_in_words(notify.created_at) %> ago
        </div> 
      </section> 
    <% end %>
  <% end %>
<% end %>

<% if @current_user.notifications.any? %>
  <% @notifications.each do |notification| %>
    <% if notification.action == 'accepted_follow_request' && notification.notifiable %> 
        <% time = notification.created_at %>
        <% exp_time = time + 38.days  %>
        <% if Time.now < exp_time  %>
          <section class="card my-5 shadow size card-background">
            <div class="card-body"> 
              <div class=" mb-3 text-light outer ">
                <% if notification.notifiable.user_accounts.any? %>
                  <% if notification.notifiable.user_accounts.first.picture.attached? %>
                    <%= image_tag @current_user.user_accounts.first.picture.url  %>
                  <% else %>
                    <%= image_tag 'default.png' %>
                  <% end %>
                <% else %>
                  <%= image_tag 'default.png' %>
                <% end %>
              </div>
              <%= link_to notification.notifiable.username, profile_path(notification.notifiable), class: "text-primary link" %> 
              accepted your connection request
              <div class = "flexrow2">
                <div class = "text-white-50">
                  <%= time_ago_in_words(notification.created_at) %> ago
                </div> 
                <div class = "text-white-50">
                  <%= button_to 'Remove', notification_path(notification), class:"link " ,method: :delete, :onclick=> "return confirm('Are you sure?')" %></div> 
                </div> 
              </div> 
            </div>
          </section> 
        <% end %> 
    <% end %> 
  <% end %>
<% end %>



    