config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :chats
  end


  namespace :api do
    namespace :v1 do
    resources :users do
    member do
      get :name
    end
    end
    end
  end

  root to: "main#index"
  get "search", to: "search#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :conversations do
    resources :messages
  end

  get "dash", to: "job_positions#job"

  resources :job_positions

  post "/job_positions/new", to: "job_positions#create"

  patch "/job_positions/:id/edit", to: "job_positions#update"

  get "/job_position/:id", to: "job_positions#destroy", as: "job_position_delete"

  resources :job_fields

  post "/job_fields/new", to: "job_fields#create"

  patch "/job_fields/:id/edit", to: "job_fields#update"

  get "/job_field/:id", to: "job_fields#destroy", as: "job_field_delete"

  get "/job_navigations/:id/edit", to: "job_navigations#edit", as: "edit_job_navigation"

  resources :job_navigations

  get "new_job_navigation", to: "job_navigations#new"

  post "/job_navigations/new", to: "job_navigations#create"

  get "/job_navigations/:id/toggle_is_approved", to: "job_navigations#toggle_is_approved",
                                                 as: "toggle_is_approved"

  get "/job_navigations/:id/destroy", to: "job_navigations#destroy", as: "job_navigation_del"

  get "/job_navigation", to: "job_navigations#show"

  resources :job_navigations, only: %i[index destroy] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  resources :job_navigations, only: %i[show] do
    resources :reviews
  end

  resources :job_navigations, only: %i[show edit] do
    resources :applies
  end

  post "/job_navigation", to: "job_navigations#show"

  resources :job_navigations do
    member do
      post "like", to: "job_navigations#vote"
    end
  end

  resources :users

  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  post "/users/:id/accept", to: "users#accept", as: "accept"
  post "/users/:id/decline", to: "users#decline", as: "decline"
  post "/users/:id/cancel", to: "users#cancel", as: "cancel"

  get "/user/:id", to: "users#destroy", as: "user_delete"

  get "notify", to: "users#notify"

  get "connection", to: "users#connection"

  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  resources :user_accounts

  get "new_user_account", to: "user_accounts#new"

  resources :job_navigations do
    resources :likes
  end

  resources :notifications

  resources :notifies

  get "/user/:id/profile", to: "users#profile", as: "profile"

  get "applied", to: "job_navigations#applied"
  get "feed", to: "job_navigations#feed"
  get "recommended", to: "users#recommended"

  get "dashboard", to: "user_accounts#dashboard"

  get "network", to: "users#network"

  get "/user/:id/follower", to: "users#follower", as: "follower"

  get "/user/:id/following", to: "users#following", as: "following"

  get "posts", to: "job_navigations#posts"

  get "/auth/:provider/callback", to: "sessions#linkedin"
  get "/auth/linkedin/callback", to: "sessions#linkedin_callback"

  get "remove_matching_user/:id", to: "users#remove_matching_user", as: "remove_matching_user"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :job_navigations, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :user_accounts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :notifies, dependent: :destroy

  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'must be a valid email address' }
  validates :username, presence: true,
                       length: { minimum: 3, maximum: 50 }
  validates :password, format: { with: %r{\A(?=.*[!@#$%^&*()\-_=+{};:,<.>‌​~\[\]|\\/])(?=.*\d).*\z},
                                 message: 'must include at least one special character and one number' },
                       length: { minimum: 4, message: 'must be at least 4 characters long' }

  scope :all_except, ->(user) { where.not(id: user) }
  scope :latest_first, -> { order(created_at: :desc) }

  attr_accessor :linkedin_uid, :linkedin_token, :linkedin_token_expiry

  def self.from_omniauth(auth)
    if auth.provider == 'linkedin'
      user = where(linkedin_uid: auth.uid).first_or_initialize
      user.linkedin_token = auth.credentials.token
      user.linkedin_token_expiry = Time.at(auth.credentials.expires_at)
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = 'default_password0@'

      user.save!
    end

    user
  end

  followability

  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    def index 
        @users = User.all
        render json: @users
    end


    def create
      @user = User.new(user_params)
      if @user.save
        render json: @user, status: :created
      else 
        render json: { error: 'Unable to create user', details: @user.errors.full_messages }, status: :unprocessable_entity
      end 
    end
   
  
    def show
        @user = User.find(params[:id])
        render json: @user
    end

    def name
      @user = User.find(params[:id]) 
      @name = @user.email
      render json: @name
    end

    private 
    def user_params
        params.require(:user).permit(:email, :username, :password, :password_confirmation)
      end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include ApplicationHelper
  before_action :set_current_user

  before_action :require_admin, only: %i[index]

  def notify; end

  def connection; end

  def list
    @userl = User.where.not(admin: true)
  end

  def index
    @users = User.where.not(admin: true)
  end

  def network
   if @current_user.user_accounts.exists?
      current_user_job = @current_user.user_accounts.first.job.downcase.split(',').map(&:strip)
      current_user_skill = @current_user.user_accounts.first.skill.downcase.split(',').map(&:strip)
      @matching_users = []
      User.joins(:user_accounts).where.not(id: @current_user.id).distinct.each do |user|
        user_job = user.user_accounts.first.job.downcase.split(',').map(&:strip)
        user_skill = user.user_accounts.first.skill.downcase.split(',').map(&:strip)
        matching_job = current_user_job & user_job
        matching_skill = current_user_skill & user_skill
        @matching_users << user if matching_job.present? || matching_skill.present?
      end
    else
      current_user_job = []
      current_user_skill = []
      @matching_users = []
      # code to render a blank page
    end
  end

  def follow
    @user = User.find(params[:id])
    @current_user.send_follow_request_to(@user)
    redirect_to request.referer
  end

  def unfollow
    @user = User.find(params[:id])
    make_it_a_unfriend_request

    @current_user.unfollow(@user)
    redirect_to request.referer
  end

  def accept
    @user = User.find(params[:id])
    @current_user.accept_follow_request_of(@user)
    make_it_a_friend_request

    @notification = Notification.create(user: @user, notifiable: @current_user, action: 'accepted_follow_request')
    redirect_to request.referer
  end

  def decline
    @user = User.find(params[:id])
    @current_user.decline_follow_request_of(@user)
    redirect_to request.referer
  end

  def cancel
    @user = User.find(params[:id])
    @current_user.remove_follow_request_for(@user)
    redirect_to request.referer
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to request.referer, notice: 'Removed the user'
    else
      redirect_to request.referer, notice: 'Couldnt remove  user'
    end
  end

  def show
    @user = User.find(params[:id])

    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @chat = Chat.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @chats = @single_room.chats.latest_first

    render 'rooms/index'
  end

  def search
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(params[:id])
  end

  def recommended
    @user = User.where.not(id: @current_user.id)
  end

  def follower
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
  end

  def remove_matching_user
    @user = User.find(params[:id])
    @user.update_attribute(:visible, false)

    if @user.update_attribute(:visible, false)

      redirect_to request.referer, notice: 'Removed the user'
    else
      puts @user.errors.full_messages # print any validation errors
      redirect_to request.referer, notice: 'Could not remove user'
    end
  end

  private

  def make_it_a_friend_request
    @current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(@current_user)
  end

  def make_it_a_unfriend_request
    @user.unfollow(@current_user) if @user.mutual_following_with?(@current_user)
  end

  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_user.html.erb
<div> <%= link_to user.username, user %> </div>

app/views/users/connection.html.erb
<% @current_user.followers.each do |user| %> 
  <section class="card my-5 shadow small card-background">
    <div class="fl">
      <div class = "outer mb3">
        <% if user.user_accounts.count > 0 %>
          <% if user.user_accounts.first.picture.attached? %>
          <%= image_tag user.user_accounts.first.picture.url  %>
          <% else %>
          <%= image_tag 'default.png' %>
          <% end %>
        <% else %>
          <%= image_tag 'default.png' %>
        <% end %>
      </div>
      <div class="card-body text-light">
        <h5><%= link_to user.username, profile_path(user), class: "text-primary link" %></h5>
        <div>
          <% if @current_user.following?(user) %>
            <%= button_to "Following", unfollow_path(user), :onclick=> "return confirm('Are you sure, You want to unfollow?')"  %>
          <% elsif @current_user.sent_follow_request_to?(user)%>
            <%= button_to "Cancel follow request", cancel_path(user)  %>
          <% elsif user.following?(@current_user) && !(@current_user.following?(user))%>
            <%= button_to "Follow Back",  follow_path(user)  %>
          <% else %>
            <%= button_to "Follow",  follow_path(user)  %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>  

app/views/users/follower.html.erb
<h4 class="center"><%= @user.username %>'s Connections</h4> 
<% @user.followers.each do |user| %> 
  <section class="card my-5 shadow small card-background">
    <div class="fl">
      <div class="card-body text-light">
        <div class = "outer mb3">
          <% if user.user_accounts.count > 0 %>
            <% if user.user_accounts.first.picture.attached? %>
              <%= image_tag user.user_accounts.first.picture.url  %>
            <% else %>
              <%= image_tag 'default.png' %>
            <% end %>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
          </div>
            <h3> --- </h3>
          <div>
            <%= link_to user.username, profile_path(user), class: "link" %> 
            <% if @current_user.following?(user) %>
              <%= button_to "Following", unfollow_path(user), :onclick=> "return confirm('Are you sure, You want to unfollow?')" %>
            <% elsif @current_user.sent_follow_request_to?(user)%>
              <%= button_to "Cancel follow request", cancel_path(user) %>
            <% elsif user.following?(@current_user) && !(@current_user.following?(user))%>
              <%= button_to "Follow Back",  follow_path(user) %>
            <% elsif user.id == @current_user.id %>
              <h6> --- </h6> 
            <% else %> 
              <%= button_to "Follow",  follow_path(user) %>
            <% end %>
      </div>
    </div>
  </section> 
<% end %>

app/views/users/following.html.erb
<h4 class="center">Users <%= @user.username %> Follow</h4> 
<% @user.following.each do |user| %> 
  <section class="card my-5 shadow small card-background">
    <div class="fl">
      <div class="card-body text-light">
        <div class = "outer mb3">
          <% if user.user_accounts.count > 0 %>
            <% if user.user_accounts.first.picture.attached? %>
              <%= image_tag user.user_accounts.first.picture.url  %>
            <% else %>
              <%= image_tag 'default.png' %>
            <% end %>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
        </div>
        <h3> --- </h3>
      <%= link_to user.username, profile_path(user), class: "link" %> 
      <% if @current_user.following?(user) %>
        <%= button_to "Following", unfollow_path(user), :onclick=> "return confirm('Are you sure, You want to unfollow?')" %>
      <% elsif @current_user.sent_follow_request_to?(user)%>
        <%= button_to "Cancel follow request", cancel_path(user) %>
      <% elsif @user.following?(@current_user) && !(@current_user.following?(@user))%>
        <%= button_to "Follow Back",  follow_path(@user) %><h6>Follow <%= @user.username %> to see their connections</h6>s
      <% elsif user.id == @current_user.id %>
        <h6> --- </h6> 
      <% else %>
        <%= button_to "Follow",  follow_path(user) %>
      <% end %>
    </div>
  </section> 
<% end %>

app/views/users/index.html.erb
<div class="container">
  <table class="table table-bordered tablesize"> 
    <thead class="table-light">
      <tr><th colspan="4"><h3 class="text-center">List Of Users</h3></th> </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="table-light">
          <td><%= user.email %></td>
          <td><%= user.username %></td>
          <td><%= user.id %></td>
          <td><%= link_to  user_delete_path(user) , method: :delete, :onclick=> "return confirm('Are you sure you want to delete this user?')" do %>
             <%= icon('fa fa-trash ') %>
            <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/network.html.erb
<% if @current_user.user_accounts.count > 0 %>
  <div class="nav-item dropdown bgin">
    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Your Interests
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <li><a class="dropdown-item" href="#">Job: <%= @current_user.user_accounts.first.job  %></a></li>
      <li><a class="dropdown-item" href="#">Skill: <%= @current_user.user_accounts.first.skill %></a></li>
    </ul>
  </div>
  <h2 class="fl" ><small class="text-dark ">Suggested Users</small></h2></br>
  <div class="wrapper">  
    <% @matching_users.each do |user| %>
      <% if user.visible %>
      <% if user.id != @current_user.id %>
        <% if !(@current_user.following?(user)) %>
          <div class="d-flex flex-row bd-highlight mb-3 network" >
            <section class="card my-5 shadow card-background">
              <div class="card-body fl">
                <div class = "outer mb3">
                  <% if user.user_accounts.count > 0 %>
                    <% if user.user_accounts.first.picture.attached? %>
                      <%= image_tag user.user_accounts.first.picture.url  %>
                    <% else %>
                      <%= image_tag 'default.png' %>
                    <% end %>
                  <% else %>
                    <%= image_tag 'default.png' %>
                  <% end %>
                </div>
                <h3>----</h3>
                <%= link_to user.username, profile_path(user), class: "pad text-primary link" %>
                <div class="mb3 pad">
                  job:<%= user.user_accounts.first.job %></br>
                  skill:<%= user.user_accounts.first.skill %>
                </div>
                <% if @current_user.following?(user) %>
                  <%= button_to "Unfollow", unfollow_path(user), :onclick=> "return confirm('Are you sure, You want to unfollow?')",class: "pad btn btn-primary" %>
                <% elsif @current_user.sent_follow_request_to?(user)%>
                  <%= button_to "Cancel follow request", cancel_path(user),class: "pad btn btn-primary" %>
                <% elsif user.following?(@current_user) && !(@current_user.following?(user))%>
                  <%= button_to "Follow Back",  follow_path(user),class: "pad btn btn-primary"  %>
                <% else %>
                  <%= button_to "Follow",  follow_path(user),class: "pad btn btn-primary" %> 
                <% end %>
                <%= link_to remove_matching_user_path(user), :onclick=> "return confirm('Are you sure you want to remove this user?')", class: "link pad text-dark d-flex flex-column align-items-center" do %>
                  <%= icon('fa fa-xmark ') %>
                <% end %>
              </div>
            </section>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/notification.html.erb
<% @current_user.follow_requests.each do |request| %>
  <section class="card my-5 shadow size" style="background-color: rgb(0,0,2) ;">
    <div class="card-body text-light">
    <% user = request.followerable %>
    <% user.user_accounts.each do |user_account| %>
        <div class=" mb-3 text-light outer ">
          <% if user_account.picture.attached? %>
            <%= image_tag user_account.picture.url  %>
          <% else %>
            <%= image_tag("https://h-o-m-e.org/wp-content/uploads/2022/04/Blank-Profile-Picture-3.jpg") %>
          <% end %>
        </div>
      <% end %>
      <%= link_to request.followerable.username, profile_path(user), class: "text-primary link" %> sent a connection request
      <%= button_to "Accept", accept_path(request.followerable) %>
      <%= button_to "Decline", decline_path(request.followerable) %>
     
    </div>
  </section>
<% end %>

<% @current_user.notifications.each do |notification| %>
  
   <% if notification.action == 'accepted_follow_request' %> 
   <section class="card my-5 shadow size" style="background-color: rgb(0,0,2) ;">
    <div class="card-body text-light"> 
    <% notification.notifiable.user_accounts.each do |user_account| %>
        <div class=" mb-3 text-light outer ">
          <% if user_account.picture.attached? %>
            <%= image_tag user_account.picture.url  %>
          <% else %>
            <%= image_tag("https://h-o-m-e.org/wp-content/uploads/2022/04/Blank-Profile-Picture-3.jpg") %>
          <% end %>
        </div>
      <% end %>
    <%= link_to notification.notifiable.username, profile_path(notification.notifiable), class: "text-primary link" %> accepted your connection request
    </div> 
    </section> 
    <% end %> 
    
    <% end %>

app/views/users/profile.html.erb
<% if @user.user_accounts.count == 0 %>
  <section class="d-flex flexrow1">
    <figure class="outer">
      <%= image_tag 'default.png' %>
    </figure>
    <div class="flexcol col1">
       <%= approved_job_count(@user) %>
      <h5>Posts</h5> 
    </div>
    <div class="flexcol col1">
      <%= @user.followers.count %>
      <% if @current_user.following?(@user) || @user.id == @current_user.id %>
        <h5> <%= link_to "Followrs", follower_path(@user), class: "text-dark" %></h5>
      <% else %>
        <h5>Followers</h5>
      <% end %> 
      </div>
      <div class="flexcol col1">
        <%= @user.following.count %>
          <% if @current_user.following?(@user) || @user.id == @current_user.id %>
            <h5> <%= link_to "Following", following_path(@user), class: "text-dark" %></h5>
          <% else %>
            <h5>Following</h5>
          <% end %> 
      </div>
  </section>
  <section>
    <div class=" mb-3 text-dark">
      <%= @user.username %>
    </div>
    <% if @current_user.following?(@user) %>
      <%= button_to "Following", unfollow_path(@user), :onclick=> "return confirm('Are you sure, You want to unfollow?')" %>
    <% elsif @current_user.sent_follow_request_to?(@user)%>
      <%= button_to "Cancel follow request", cancel_path(@user) %>
    <% elsif @user.following?(@current_user) && !(@current_user.following?(@user))%>
      <%= button_to "Follow Back",  follow_path(@user) %><h6>Follow <%= @user.username %> to see their connections</h6>
    <% elsif @user.id == @current_user.id %>
      <h6> --- </h6> 
    <% else %>
      <%= button_to "Follow",  follow_path(@user) %><h6>Follow <%= @user.username %> to see their connections</h6>
    <% end %>
  </section>
<% else %>
  <% @user.user_accounts.each do |user_account| %>
    <section class="d-flex flexrow1">
      <figure class="outer">
        <% if user_account.picture.attached? %>
          <%= image_tag user_account.picture.url  %>
        <% else %>
          <%= image_tag 'default.png' %>
        <% end %>
      </figure>
      <div class="flexcol col1">
        <%= approved_job_count(@user) %>
        <h5>Posts</h5> 
      </div>
      <div class="flexcol col1">
        <%= @user.followers.count %>
        <% if @current_user.following?(@user) || @user.id == @current_user.id %>
          <h5> <%= link_to "Followers", follower_path(@user), class: "text-dark" %></h5>
            <% else %>
          <h5>Followers</h5>
        <% end %> 
      </div>
      <div class="flexcol col1">
        <%= @user.following.count %>
            <% if @current_user.following?(@user) || @user.id == @current_user.id %>
            <h5> <%= link_to "Following", following_path(@user), class: "text-dark" %></h5>
            <% else %>
          <h5>Following</h5>
        <% end %> 
      </div>
    </section>
    <section>
      <div class=" mb-3 text-dark">
        <%= @user.username %>
      </div>
      <div class=" mb-3 text-dark">
        <%= user_account.organisation %>
      </div>
      <div class=" mb-3 text-dark">
        <%= user_account.bio %>
      </div>
    </section>
  <% end %>
  <% if @current_user.following?(@user) %>
    <%= button_to "Following", unfollow_path(@user), :onclick=> "return confirm('Are you sure, You want to unfollow?')" %>
  <% elsif @current_user.sent_follow_request_to?(@user)%>
    <%= button_to "Cancel follow request", cancel_path(@user) %>
  <% elsif @user.following?(@current_user) && !(@current_user.following?(@user))%>
    <%= button_to "Follow Back",  follow_path(@user) %><h6>Follow <%= @user.username %> to see their connections</h6>
  <% elsif @user.id == @current_user.id %>
    <h6> --- </h6> 
  <% else %>
    <%= button_to "Follow",  follow_path(@user) %><h6>Follow <%= @user.username %> to see their connections</h6>
  <% end %>
<% end %>
<section class="wrapperjob center">
  <% @user.job_navigations.order(created_at: :desc).each do |job_navigation| %>
    <% pre_apply = job_navigation.applies.find {|apply| apply.user_id == @current_user.id} %>
      <% if job_navigation.is_approved == true  %> 
        <section class="card my-5 shadow card-background"> 
          <div class="card-body">
            <div class=" mb-3 ">
              <h5>JOB TITLE : </h5>
              <%= job_navigation.jobtitle%>
            </div>
            <div class=" mb-3 ">
              <h5>JOB DESCRIPTION :</h5>
              <%= job_navigation.jobdescription %>
            </div>
            <div class=" mb-3 "> 
              <h5>NUMBER OF VACANCY :</h5>
              <%= job_navigation.vacancy %>
            </div>
            <div class=" mb-3">
              <h5>SKILL:</h5>
              <%= job_navigation.skill%>
            </div>
            <div class=" mb-3 ">
              <h5>JOB ROLE:</h5>
              <%= job_navigation.jobrole%>
            </div>
            <div class=" mb-3 ">
              <h5>JOB SECTOR:</h5>
              <%= job_navigation.jobsector%>
            </div>
            <p class=" mb-3 "><%= job_navigation.likes.count %> <%= (job_navigation.likes.count) == 1 ? 'Like' : 'Likes' %></p>
              <% pre_like = job_navigation.likes.find {|like| like.user_id == @current_user.id} %>
                <% if pre_like %>
                  <%= button_to 'Unlike', job_navigation_like_path(job_navigation, pre_like), method: :delete %>
                <% else %>
                  <%= button_to 'Like', job_navigation_likes_path(job_navigation), method: :post %>
                <% end %>
              <%= link_to 'Details', job_navigation_path(job_navigation), class:"text-primary link"  %>
          </div>
        </section>  
      <% end %>
  <% end %>
</section>  

          

         