config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :chats
  end


  namespace :api do
    namespace :v1 do
    resources :users do
    member do
      get :name
    end
    end
    end
  end

  root to: "main#index"
  get "search", to: "search#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :conversations do
    resources :messages
  end

  get "dash", to: "job_positions#job"

  resources :job_positions

  post "/job_positions/new", to: "job_positions#create"

  patch "/job_positions/:id/edit", to: "job_positions#update"

  get "/job_position/:id", to: "job_positions#destroy", as: "job_position_delete"

  resources :job_fields

  post "/job_fields/new", to: "job_fields#create"

  patch "/job_fields/:id/edit", to: "job_fields#update"

  get "/job_field/:id", to: "job_fields#destroy", as: "job_field_delete"

  get "/job_navigations/:id/edit", to: "job_navigations#edit", as: "edit_job_navigation"

  resources :job_navigations

  get "new_job_navigation", to: "job_navigations#new"

  post "/job_navigations/new", to: "job_navigations#create"

  get "/job_navigations/:id/toggle_is_approved", to: "job_navigations#toggle_is_approved",
                                                 as: "toggle_is_approved"

  get "/job_navigations/:id/destroy", to: "job_navigations#destroy", as: "job_navigation_del"

  get "/job_navigation", to: "job_navigations#show"

  resources :job_navigations, only: %i[index destroy] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  resources :job_navigations, only: %i[show] do
    resources :reviews
  end

  resources :job_navigations, only: %i[show edit] do
    resources :applies
  end

  post "/job_navigation", to: "job_navigations#show"

  resources :job_navigations do
    member do
      post "like", to: "job_navigations#vote"
    end
  end

  resources :users

  post "/users/:id/follow", to: "users#follow", as: "follow"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow"
  post "/users/:id/accept", to: "users#accept", as: "accept"
  post "/users/:id/decline", to: "users#decline", as: "decline"
  post "/users/:id/cancel", to: "users#cancel", as: "cancel"

  get "/user/:id", to: "users#destroy", as: "user_delete"

  get "notify", to: "users#notify"

  get "connection", to: "users#connection"

  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  resources :user_accounts

  get "new_user_account", to: "user_accounts#new"

  resources :job_navigations do
    resources :likes
  end

  resources :notifications

  resources :notifies

  get "/user/:id/profile", to: "users#profile", as: "profile"

  get "applied", to: "job_navigations#applied"
  get "feed", to: "job_navigations#feed"
  get "recommended", to: "users#recommended"

  get "dashboard", to: "user_accounts#dashboard"

  get "network", to: "users#network"

  get "/user/:id/follower", to: "users#follower", as: "follower"

  get "/user/:id/following", to: "users#following", as: "following"

  get "posts", to: "job_navigations#posts"

  get "/auth/:provider/callback", to: "sessions#linkedin"
  get "/auth/linkedin/callback", to: "sessions#linkedin_callback"

  get "remove_matching_user/:id", to: "users#remove_matching_user", as: "remove_matching_user"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if @current_user && !(@current_user.admin) %>
  <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
    <%= link_to dashboard_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
      <%= icon('fa fa-linkedin fa-2x') %>
      <span class="small d-flex flex-column align-items-center">linkedin</span>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul>
      <li class="nav-item active">
        <%= link_to connection_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
        <%= icon('fa fa-users fa-2x') %>
        <span class="small d-flex flex-column align-items-center">Connections</span>
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to network_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
        <%= icon('fa fa-user fa-2x ') %>
        <span class="small d-flex flex-column align-items-center">Network</span>
        <% end %>
      </li>
      <li class="nav-item dropdown text-primary">
        <a class="nav-link dropdown-toggle text-primary" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= icon('fa-sharp fa-solid fa-user-tie fa-2x') %><br>
          <span class="small dropdown ">Job</span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li class="dropdown-item"><%= link_to "Recruite", new_job_navigation_path, class:"link"  %></li>
          <li class="dropdown-item"><%= link_to "Apply", job_navigations_path, class:"link"  %></li>
          <li class="dropdown-item"><%= link_to "Recommended", feed_path, class:"link"  %></li>
          <li><hr class="dropdown-divider"></li>
          <li class="dropdown-item"><%= link_to "Applied Jobs", applied_path, class:"link"  %></li>
        </ul>
      </li>
      <li class="nav-item">
        <%= link_to rooms_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
          <%= icon('fa-sharp fa-regular fa-message fa-2x') %>
          <span class="small d-flex flex-column align-items-center">Message</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to notifications_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
          <%= icon('fa fa-bell fa-2x') %>
          <span class="small d-flex flex-column align-items-center">Notification</span>
        <% end %>
      </li>
      </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= render 'search/form' %>
      </li>
      <li class="nav-item dropdown text-primary navpic flex-row">
        <a class="nav-link dropdown-toggle text-primary" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if @current_user.user_accounts.count > 0 %>
            <% if @current_user.user_accounts.first.picture.attached? %>
              <%= image_tag @current_user.user_accounts.first.picture.url %>
            <% else %>
                <%= image_tag 'default.png' %>
            <% end %>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
          <span class="small dropdown "><%= @current_user.email %></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li class="dropdown-item"><%= link_to "Information", user_accounts_path, class:"link"  %></li>
          <li class="dropdown-item"><%= link_to "Your Profile", profile_path(@current_user), class:"link"  %></li>
          <li class="dropdown-item"><%= link_to "Logout", logout_path, class:"link"  %></li>
          <li class="dropdown-item"><%= link_to "Edit Password", password_path, class:"link"  %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<% end %>
<% if @current_user && (@current_user.admin) %>
  <nav class="navbar navbar-expand-lg bg-light justify-content-between">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav text-center">
          <li class="nav-item">
            <%= link_to dash_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
              <%= icon('fa fa-house fa-2x') %>
              <span class="small d-flex flex-column align-items-center">Home</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to job_positions_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
              <%= icon('fa fa-user') %>
              <span class="small d-flex flex-column align-items-center">Job Role</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to job_fields_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
              <%= icon('fa fa-building ') %>
              <span class="small d-flex flex-column align-items-center">Job Sector</span>
            <% end %>
          </li>
            <li class="nav-item">
              <%= link_to job_navigations_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
                <%= icon('fa fa-paste ') %>
                <span class="small d-flex flex-column align-items-center">Job Applications</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "btn btn-outline-light text-primary d-flex flex-column align-items-center" do %>
                <%= icon('fa fa-users fa-2x') %>
                <span class="small d-flex flex-column align-items-center">Users</span>
              <% end %>
            </li>
            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
                <%= @current_user.email %>
              </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li class="dropdown-item "><%= link_to "Edit Password", password_path , class:"link" %></li>
                  <li class="dropdown-item "><%= link_to "Logout", logout_path , class:"link" %></li>
                  </ul>
              </li>
              </ul>
      </div>
    </div>
  </nav>
<% end %>



   
    
  





    
         

   